table DimState
	lineageTag: 8383a265-dcfe-47d2-89cb-654f2dcbfd9d

	column State
		dataType: string
		lineageTag: 0409ab3d-250e-4915-8ac3-3ced601b19b7
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column stateID
		dataType: int64
		formatString: 0
		lineageTag: 8e91143f-654b-494a-ad21-8e22e6a1f3e1
		summarizeBy: none
		sourceColumn: stateID

		annotation SummarizationSetBy = Automatic

	partition DimState = m
		mode: import
		source =
				let
				    Source = Data,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"State"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "stateID"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

